<?php
/**
 * Default configuration parameters for new installations / updates.
 * Used by DatabaseManager and update.php — do not duplicate elsewhere.
 */
function getConfigDefaults() {
    return array(
        array(
            'Parameter' => 'styleAppmntUnpublished',
            'Value' => 'w3-opacity',
            'Type' => 'string',
            'Description' => 'Stil f&uuml;r versteckte Termine (leere Sichtbarkeit / Admin-only)',
        ),
        array(
            'Parameter' => 'colorLogDefault',
            'Value' => '#FDFFFC',
            'Type' => 'color',
            'Description' => 'Farbe von DEFAULT Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorLogFatal',
            'Value' => '#F44336',
            'Type' => 'color',
            'Description' => 'Farbe von FATAL Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorLogError',
            'Value' => '#FFC300',
            'Type' => 'color',
            'Description' => 'Farbe von ERROR Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorLogWarning',
            'Value' => '#FFC300',
            'Type' => 'color',
            'Description' => 'Farbe von WARNING Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorLogDBDelete',
            'Value' => '#FDFFFC',
            'Type' => 'color',
            'Description' => 'Farbe von DB DELETE Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorLogDBInsert',
            'Value' => '#FDFFFC',
            'Type' => 'color',
            'Description' => 'Farbe von DB INSERT Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorLogDBUpdate',
            'Value' => '#FDFFFC',
            'Type' => 'color',
            'Description' => 'Farbe von DB UPDATE Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorLogEmail',
            'Value' => '#FDFFFC',
            'Type' => 'color',
            'Description' => 'Farbe von EMAIL Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorLogInfo',
            'Value' => '#FDFFFC',
            'Type' => 'color',
            'Description' => 'Farbe von INFO Logeintr&auml;gen',
        ),
        array(
            'Parameter' => 'colorUserMember',
            'Value' => '#345A95',
            'Type' => 'color',
            'Description' => 'Farbe von Vereinsmitgliedern',
        ),
        array(
            'Parameter' => 'colorUserNoMember',
            'Value' => '#FDF9E7',
            'Type' => 'color',
            'Description' => 'Farbe von Nicht-Vereinsmigliedern',
        ),
        array(
            'Parameter' => 'colorAppmntConcert',
            'Value' => '#FDF9E7',
            'Type' => 'color',
            'Description' => 'Farbe von Konzertauftritten',
        ),
        array(
            'Parameter' => 'colorAppmntNoConcert',
            'Value' => '#FDFFFC',
            'Type' => 'color',
            'Description' => 'Farbe von sonstigen Auftritten',
        ),
        array(
            'Parameter' => 'colorAppmntYes',
            'Value' => '#004D33',
            'Type' => 'color',
            'Description' => 'Farbe von zugesagten Terminen',
        ),
        array(
            'Parameter' => 'colorAppmntNo',
            'Value' => '#A6001A',
            'Type' => 'color',
            'Description' => 'Farbe von abgesagten Terminen',
        ),
        array(
            'Parameter' => 'colorAppmntMaybe',
            'Value' => '#00477E',
            'Type' => 'color',
            'Description' => 'Farbe von unsicheren Terminen',
        ),
        array(
            'Parameter' => 'colorBtnYes',
            'Value' => '#4CAF50',
            'Type' => 'color',
            'Description' => 'Farbe von Ja-Buttons',
        ),
        array(
            'Parameter' => 'colorBtnNo',
            'Value' => '#F44336',
            'Type' => 'color',
            'Description' => 'Farbe von Nein-Buttons',
        ),
        array(
            'Parameter' => 'colorBtnMaybe',
            'Value' => '#2196F3',
            'Type' => 'color',
            'Description' => 'Farbe von Vielleicht-Buttons',
        ),
        array(
            'Parameter' => 'colorDisabled',
            'Value' => '#9E9E9E',
            'Type' => 'color',
            'Description' => 'Farbe von deaktivierten Elementen',
        ),
        array(
            'Parameter' => 'colorBtnEdit',
            'Value' => '#009688',
            'Type' => 'color',
            'Description' => 'Farbe von Edit-Buttons',
        ),
        array(
            'Parameter' => 'HoverEffect',
            'Value' => 'w3-hover-gray',
            'Type' => 'string',
            'Description' => 'Stil des Hover-Effekts',
        ),
        array(
            'Parameter' => 'colorSuccess',
            'Value' => '#4CAF50',
            'Type' => 'color',
            'Description' => 'Farbe von Erfolgsmeldungen',
        ),
        array(
            'Parameter' => 'colorNav',
            'Value' => '#969696',
            'Type' => 'color',
            'Description' => 'Farbe der Navigationsleiste',
        ),
        array(
            'Parameter' => 'colorNavAdmin',
            'Value' => '#607D8B',
            'Type' => 'color',
            'Description' => 'Farbe der Admin-Navigationsleiste',
        ),
        array(
            'Parameter' => 'SubjectReminder',
            'Value' => 'Erinnerung',
            'Type' => 'string',
            'Description' => 'Betreff der Erinnerungsmail',
        ),
        array(
            'Parameter' => 'SubjectPW',
            'Value' => 'neues Passwort',
            'Type' => 'string',
            'Description' => 'Betreff der Email mit neuem Passwort',
        ),
        array(
            'Parameter' => 'MailGreetings',
            'Value' => 'Dein Musikverein Bonn-Duisdorf',
            'Type' => 'string',
            'Description' => 'Gru&szlig;formel unter System-Emails',
        ),
        array(
            'Parameter' => 'cronSendnewAppmnts',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Sende Nachricht, wenn neue Termine erstellt wurden.',
        ),
        array(
            'Parameter' => 'cronSendnewAppmntsDays',
            'Value' => '64',
            'Type' => 'days',
            'Description' => 'Sende Nachricht, wenn neue Termine erstellt wurden an folgenden Tagen.',
        ),
        array(
            'Parameter' => 'cronSendnewAppmntsTime',
            'Value' => '14:00',
            'Type' => 'time',
            'Description' => 'Sende Nachricht, wenn neue Termine erstellt zu folgender Uhrzeit.',
        ),
        array(
            'Parameter' => 'cronSendnewAppmntsInMail',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Zeige neue Termine in der Email.',
        ),
        array(
            'Parameter' => 'cronSendnewAppmntsText',
            'Value' => 'bitte folgende neue Termine vormerken',
            'Type' => 'text',
            'Description' => 'Text der Email mit neuen Terminen.',
        ),
        array(
            'Parameter' => 'cronSendTomorrow',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Sende Nachricht, wenn Termin am folgenden Tag ansteht.',
        ),
        array(
            'Parameter' => 'cronSendTomorrowTime',
            'Value' => '14:00',
            'Type' => 'time',
            'Description' => 'Sende Nachricht, wenn Termin am folgenden Tag ansteht zu folgender Uhrzeit.',
        ),
        array(
            'Parameter' => 'AppmntAlwaysDecline',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Man kann sich auch von bereits geschlossenen Anmeldungen abmelden.',
        ),
        array(
            'Parameter' => 'showOrchestraView',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Zeige einen Sitzplan des Orchesters in allen Meldungen',
        ),
        array(
            'Parameter' => 'showOrchestraRegisterBands',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Hinterlege Registerbereiche im Orchester-Sitzplan mit farbigen B&ouml;gen',
        ),
        array(
            'Parameter' => 'MessageOfTheDay',
            'Value' => '',
            'Type' => 'text',
            'Description' => 'Nachricht, die jedem Nutzen beim Einloggen angezeigt wird.',
        ),
        array(
            'Parameter' => 'MessageOfTheDayShort',
            'Value' => '',
            'Type' => 'text',
            'Description' => 'Zusammenfassung der Nachricht, die jedem Nutzen beim Einloggen angezeigt wird.',
        ),
        array(
            'Parameter' => 'showAddToCalendarButton',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Zeige Button zum Erstellen von Kalendereinträgen',
        ),
        array(
            'Parameter' => 'alwaysYesNewAppmnts',
            'Value' => '',
            'Type' => 'string',
            'Description' => 'Nutzer, die automatisch in neue Termine mit Ja eingetragen werden (userID durch Komma getrennt)',
        ),
        array(
            'Parameter' => 'showMessageOfTheDay',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Zeige Nachricht, die jedem Nutzen beim Einloggen angezeigt wird.',
        ),
        array(
            'Parameter' => 'orgName',
            'Value' => 'Musikverein Bonn-Duisdorf gegr. 1949 e.V.',
            'Type' => 'string',
            'Description' => 'Vereinsname',
        ),
        array(
            'Parameter' => 'orgNameShort',
            'Value' => 'Musikverein Duisdorf',
            'Type' => 'string',
            'Description' => 'Vereinsname (kurz)',
        ),
        array(
            'Parameter' => 'numberOfDaysInHistory',
            'Value' => '7',
            'Type' => 'uint',
            'Description' => 'Anzahl der Tage in der Statistikberechnung',
        ),
        array(
            'Parameter' => 'inactiveUsersDays',
            'Value' => '90',
            'Type' => 'uint',
            'Description' => 'Nutzer gelten in der Statistik als inaktiv, wenn letzter Login und letzte Teilnahme älter sind (Tage)',
        ),
        array(
            'Parameter' => 'calendarPastDays',
            'Value' => '0',
            'Type' => 'uint',
            'Description' => 'Termine im Kalender anzeigen, die wieviele Tage alt sind',
        ),
        array(
            'Parameter' => 'alwaysMaybeNewAppmnts',
            'Value' => '',
            'Type' => 'string',
            'Description' => 'Nutzer, die automatisch in neue Termine mit Vielleicht eingetragen werden (userID durch Komma getrennt)',
        ),
        array(
            'Parameter' => 'DiscordWebHookURL',
            'Value' => '',
            'Type' => 'string',
            'Description' => 'URL für den Discord Webhook',
        ),
        array(
            'Parameter' => 'DiscordAvatarURL',
            'Value' => '',
            'Type' => 'string',
            'Description' => 'URL für den Discord Bot-Avatar',
        ),
        array(
            'Parameter' => 'DiscordBotName',
            'Value' => 'Bot',
            'Type' => 'string',
            'Description' => 'Anzeigename des Discord Bots',
        ),
        array(
            'Parameter' => 'showBranchBannerAlways',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Branch-Banner auch auf master anzeigen',
        ),
        array(
            'Parameter' => 'WebSiteName',
            'Value' => 'Meldeliste - Musikverein Bonn-Duisdorf',
            'Type' => 'string',
            'Description' => 'Name der Website (Titel)',
        ),
        array(
            'Parameter' => 'WebSiteNameShort',
            'Value' => 'Meldeliste - MVD',
            'Type' => 'string',
            'Description' => 'Kurzer Website-Name (mobil)',
        ),
        array(
            'Parameter' => 'WebSiteURL',
            'Value' => 'http://localhost:8080',
            'Type' => 'string',
            'Description' => 'Basis-URL der Meldeliste',
        ),
        array(
            'Parameter' => 'MasterPage',
            'Value' => 'https://www.musikverein-bonn-duisdorf.de',
            'Type' => 'string',
            'Description' => 'URL der Vereinshomepage',
        ),
        array(
            'Parameter' => 'MasterPageIcon',
            'Value' => 'imgs/MVDLogo32x32.png',
            'Type' => 'string',
            'Description' => 'Icon für Link zur Vereinshomepage (Login o. Ä.)',
        ),
        array(
            'Parameter' => 'MediaDiscordURL',
            'Value' => '',
            'Type' => 'string',
            'Description' => 'Medien: Discord-Einladungs-URL (leer = ausgeblendet)',
        ),
        array(
            'Parameter' => 'MediaYoutubeURL',
            'Value' => 'https://www.youtube.com/playlist?list=PLcnXPttCC4m4ZrvzYxJf4_tTIBwRjhDDo',
            'Type' => 'string',
            'Description' => 'Medien: YouTube-URL (leer = ausgeblendet)',
        ),
        array(
            'Parameter' => 'MediaInstagramURL',
            'Value' => '',
            'Type' => 'string',
            'Description' => 'Medien: Instagram-URL (leer = ausgeblendet)',
        ),
        array(
            'Parameter' => 'MediaFacebookURL',
            'Value' => '',
            'Type' => 'string',
            'Description' => 'Medien: Facebook-URL (leer = ausgeblendet)',
        ),
        array(
            'Parameter' => 'MediaPhotosURL',
            'Value' => 'https://cloud.musikverein-bonn-duisdorf.de/index.php/s/CorLLnP3Znnxd8E',
            'Type' => 'string',
            'Description' => 'Medien: Fotos/Bilder-URL (leer = ausgeblendet)',
        ),
        array(
            'Parameter' => 'MediaVideosURL',
            'Value' => 'https://cloud.musikverein-bonn-duisdorf.de/index.php/s/3nz6GTtJWCLESfx',
            'Type' => 'string',
            'Description' => 'Medien: Video-URL (leer = ausgeblendet)',
        ),
        array(
            'Parameter' => 'MediaAudioURL',
            'Value' => '',
            'Type' => 'string',
            'Description' => 'Medien: Audio-URL (leer = ausgeblendet)',
        ),
        array(
            'Parameter' => 'AdminEmail',
            'Value' => 'meldeliste@musikverein-bonn-duisdorf.de',
            'Type' => 'string',
            'Description' => 'Admin-Emailadresse',
        ),
        array(
            'Parameter' => 'favicon',
            'Value' => 'imgs/MVDLogo32x32.png',
            'Type' => 'string',
            'Description' => 'Favicon-URL oder Pfad',
        ),
        array(
            'Parameter' => 'colorBackground',
            'Value' => '#FDFFFC',
            'Type' => 'color',
            'Description' => 'Hintergrundfarbe der Seite',
        ),
        array(
            'Parameter' => 'colorTitle',
            'Value' => '#FDF9E7',
            'Type' => 'color',
            'Description' => 'Farbe der Titelzeile',
        ),
        array(
            'Parameter' => 'colorTitleBar',
            'Value' => '#345A95',
            'Type' => 'color',
            'Description' => 'Farbe von Seiten-Titelleisten',
        ),
        array(
            'Parameter' => 'colorWarning',
            'Value' => '#FDF9E7',
            'Type' => 'color',
            'Description' => 'Farbe von Warnhinweisen',
        ),
        array(
            'Parameter' => 'colorBtnSubmit',
            'Value' => '#9C27B0',
            'Type' => 'color',
            'Description' => 'Farbe von Submit-Buttons',
        ),
        array(
            'Parameter' => 'colorBtnDelete',
            'Value' => '#F44336',
            'Type' => 'color',
            'Description' => 'Farbe von Löschen-Buttons',
        ),
        array(
            'Parameter' => 'colorInputBackground',
            'Value' => '#F1F1F1',
            'Type' => 'color',
            'Description' => 'Hintergrundfarbe von Eingabefeldern',
        ),
        array(
            'Parameter' => 'showMembers',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Mitgliederliste anzeigen',
        ),
        array(
            'Parameter' => 'showNonMembers',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Nicht-Mitgliederliste anzeigen',
        ),
        array(
            'Parameter' => 'showConductor',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Dirigent in Listen anzeigen',
        ),
        array(
            'Parameter' => 'showRegisterLead',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Registerführer anzeigen',
        ),
        array(
            'Parameter' => 'showTravelTime',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Abfahrtszeit anzeigen',
        ),
        array(
            'Parameter' => 'showVehicle',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Fahrzeug anzeigen',
        ),
        array(
            'Parameter' => 'showGuestOption',
            'Value' => '1',
            'Type' => 'bool',
            'Description' => 'Gäste-Option bei Meldungen',
        ),
        array(
            'Parameter' => 'showChildOption',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Kinder-Option bei Meldungen',
        ),
        array(
            'Parameter' => 'statusPerMail',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Status per Email senden',
        ),
        array(
            'Parameter' => 'cronSendReminder',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Erinnerungsmails per Cron senden',
        ),
        array(
            'Parameter' => 'cronSendReminderDays',
            'Value' => '64',
            'Type' => 'days',
            'Description' => 'Erinnerungsmails an folgenden Tagen',
        ),
        array(
            'Parameter' => 'cronSendReminderTime',
            'Value' => '14:00',
            'Type' => 'time',
            'Description' => 'Uhrzeit für Erinnerungsmails',
        ),
        array(
            'Parameter' => 'cronMailQueueBatchSize',
            'Value' => '20',
            'Type' => 'uint',
            'Description' => 'Anzahl Emails pro Cron-Lauf der Mail-Queue',
        ),
        array(
            'Parameter' => 'cronMailQueueMaxAttempts',
            'Value' => '3',
            'Type' => 'uint',
            'Description' => 'Maximale Versandversuche pro Queue-Eintrag',
        ),
        array(
            'Parameter' => 'newMailSubject',
            'Value' => 'Willkommen',
            'Type' => 'string',
            'Description' => 'Betreff der Willkommensmail',
        ),
        array(
            'Parameter' => 'newMailText',
            'Value' => 'willkommen in der Meldeliste.',
            'Type' => 'text',
            'Description' => 'Text der Willkommensmail',
        ),
        array(
            'Parameter' => 'colorSchemeActive',
            'Value' => 'classic',
            'Type' => 'string',
            'Description' => 'Aktives Farbschema (classic, light, dark, gold, soft)',
        ),
        array(
            'Parameter' => 'colorSchemes',
            'Value' => '',
            'Type' => 'internal',
            'Description' => 'Gespeicherte Farbschemata (JSON, intern)',
        ),
        array(
            'Parameter' => 'regNumberInstrumentsMigrated',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Instrument-RegNumbers dem INSTR-Kreis zugeordnet',
        ),
        array(
            'Parameter' => 'visibilitySpecFromPublishedMigrated',
            'Value' => '0',
            'Type' => 'bool',
            'Description' => 'Termine.published nach VisibilitySpec (Alle User) migriert',
        ),
        array(
            'Parameter' => 'SchemaVersion',
            'Value' => '0',
            'Type' => 'int',
            'Description' => 'Installierte DB-Schema-Version (Soll: config/SchemaVersion.php)',
        ),
    );
}
?>
