<div class="w3-container w3-margin-top"><p><b>Kurzanleitung:</b></p>
<table>
<tbody>
<row>
<td>
<ul>
	<li>
		<p><i class="fas fa-home"></i> - Home</p>
		<p>Startseite der Meldeliste - hier werden die n&auml;chsten f&uuml;nf Termine angezeigt.</p>
	</li>
	<li>
		<p><i class="far fa-calendar-alt"></i> - Termine</p>
		<p>Hier werde alle zuk&uuml;nftigen Termine angezeigt.</p>
	</li>
	<li>
		<p><i class="fas fa-users"></i> - Mein Register</p>
		<p>Anzeige der R&uuml;ckmeldungen des eigenen Registers:</p>
		<ul>
			<li><div class="w3-green">Gr&uuml;n:&nbsp;Kommt</div></li>
			<li><div class="w3-red">Rot:&nbsp;&nbsp;&nbsp;Kommt nicht</div></li>
			<li><div class="w3-blue">Blau:&nbsp;Noch offen</div></li>
		</ul>
	</li>
	<li>
		<p><i class="fas fa-user"></i> - Mein Profil</p>
		<p>Anzeige der eigenen Profildaten</p>
	</li>
	<li>
		<p><img class="w3-gray" src="https://www.musikverein-bonn-duisdorf.de/WappenICO.png" /> - Vereinshomepage</p>
		<p>&Ouml;ffnet die Vereinshomepage in einem eigenen Tab</p>
	</li>
	<li>
		<p><i class="fas fa-info"></i> - Info/Hilfe</p>
		<p>Diese Seite</p>
	</li>
	<li>
		<p><i class="fas fa-sign-out-alt"></i> - Ausloggen</p>
		<p>Beendet die aktuelle Sitzung</p>
	</li>
</ul>
</td><td></td>
</row>
</tbody>
</table>
</div>