<div class="w3-container w3-margin-top"><p><b>Kurzanleitung:</b></p>
<ul>
	<li>
		<p><i class="fas fa-home"> - Home</i></p>
		<p>Startseite der Meldeliste - hier werden die n&auml;chsten f&uuml;nf Termine angezeigt.</p>
	</li>
	<li>
		<p><i class="fas fa-calendar-alt"> - Termine</i></p>
		<p>Hier werde alle zuk&uuml;nftigen Termine angezeigt.</p>
	</li>
	<li>
		<p><i class="fas fa-users"> - Mein Register</i></p>
		<p>Anzeige der R&uuml;ckmeldungen des eigenen Registers:</p>
		<ul>
			<li><div class="w3-green">Gr&uuml;n:&nbsp;Kommt</div></li>
			<li><div class="w3-red">Rot:&nbsp;&nbsp;&nbsp;Kommt nicht</div></li>
			<li><div class="w3-blue">Blau:&nbsp;Noch offen</div></li>
		</ul>
	</li>
	<li>
		<p><i class="fas fa-user"> - Mein Profil</i></p>
		<p>Anzeige der eigenen Profildaten</p>
	</li>
	<li>
		<p><img src="https://www.musikverein-bonn-duisdorf.de/WappenICO.png" /> <i class="fas"> - Vereinshomepage</i></p>
		<p>&Ouml;ffnet die Vereinshomepage in einem eigenen Tab</p>
	</li>
	<li>
		<p><i class="fas fa-info"> - Info/Hilfe</i></p>
		<p>Diese Seite</p>
	</li>
	<li>
		<p><i class="fas fa-sign-out-alt"> - Ausloggen</i></p>
		<p>Beendet die aktuelle Sitzung</p>
	</li>
</ul>
</div>